name:                hasktorch-nlp-introduction
version:             0.1.0.0
github:              "githubuser/hasktorch-nlp-introduction"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hasktorch-nlp-introduction#readme>

dependencies:
- base >= 4.7 && < 5
- hasktorch
- bytestring
- jsonl
- aeson
- utf8-string
- containers

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  day6:
    main:                amazonReview.hs
    source-dirs:         Day6
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hasktorch-nlp-introduction
  day5-bow:
    main:                bow.hs
    source-dirs:         Day5
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hasktorch-nlp-introduction


tests:
  hasktorch-nlp-introduction-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hasktorch-nlp-introduction
